### ISSUE TITLE
Add $HOME/.local/bin to $PATH during installation

### ISSUE THREAD

**Issue by jpantao** [jmg-duarte/scrape-the-box#2]
`export PATH="$HOME/.local/bin:$PATH"` should do it.

**Comment by jmg-duarte** [comment]
Based on [this](https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path) I don't think the script should be allowed to do so.

Furthermore `export` would not resolve the issue as it only works for the current shell session and it is a `bash`built-in function. 

For more information, see [here](https://www.tutorialspoint.com/unix_commands/export.htm).

However I will look into placing the `stb` executable in a more suitable place.
